
#---- debian build environment ----
FROM debian:11 as deb11buildos
RUN apt-get update && \
    apt-get install -y make python3 python3-configobj python3-setuptools build-essential debhelper git

#--- build debian packages ---
FROM deb11buildos as deb11buildenv
RUN git clone https://github.com/weewx/weewx.git /root/weewx && \
    cd /root/weewx && make debian-packages 

#--- grab the results ---
FROM debian:11 as results.debian
COPY --from=deb11buildenv   /root/weewx/dist/* /root/
